version: '3.7'
services:
  bot-mongo-express:
    image: mongo-express
    ports:
      - "8881:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: arthur
      ME_CONFIG_BASICAUTH_PASSWORD: MongoExpress2019!
      ME_CONFIG_MONGODB_PORT: 37017
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongo_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongo_secret
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    depends_on:
      - bot-mongo
    networks:
      - bot-compose-network

  bot-mongo:
    image: mongo
    restart: always
    ports:
     - "37017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_user
      MONGO_INITDB_ROOT_PASSWORD: mongo_secret
      MONGO_INITDB_DATABASE: voucher
      MONGO_INITDB_DATABASE: voucher
#    volumes:
#      - /Users/arthur.landim/projects/voucher_dices/MongoDB:/data/db
    networks:
      - bot-compose-network

networks: 
    bot-compose-network:
      driver: bridge